version: "3.4"
services:
  sample:
    image: node-app:latest
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node-app
    ports:
     - 3000:3000
#change in demo
